<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>RfqInstaller.Uninstall</AssemblyName>
    <RootNamespace>RfqInstaller.Uninstall</RootNamespace>
    <Product>RFQ Application Uninstall</Product>
    <AssemblyTitle>RFQ Application Uninstall</AssemblyTitle>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RfqInstaller.Core\RfqInstaller.Core.csproj" />
  </ItemGroup>

</Project>
